=== uo277915/sew_ext_2022/xml/friendships.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es/alumnos" 
	elementFormDefault="qualified" 
	targetNamespace="http://www.uniovi.es/alumnos" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="usuarios">
		<xs:complexType>
			<xs:sequence>
                <!-- Puede haber infinitos usuarios -->
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="usuario" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="usuario">
		<xs:complexType>
			<xs:sequence>
                <!-- Cada usuario puede tener un grupo de datos y un grupo de amigos, pero no obligatoriamiente -->
				<xs:element minOccurs="0" maxOccurs="1" ref="datos" />
				<xs:element minOccurs="0" maxOccurs="1" ref="amigos" />
			</xs:sequence>
            <!-- La id es un numero obligatorio -->
			<xs:attribute name="id" type="xs:int" use="required" />
            <!-- El nickname es un string obligatorio -->
			<xs:attribute name="nickname" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="datos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fechaNacimiento" />
				<xs:element ref="estado" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fotoPerfil" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaNacimiento">
		<xs:complexType>
			<xs:attribute name="dia" type="diaTipo" use="required" />
			<xs:attribute name="mes" type="mesTipo" use="required" />
			<xs:attribute name="a침o" type="a침oTipo" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="estado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="mensaje" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotoPerfil">
		<xs:complexType>
			<!-- Las fotos de perfil deben ser URLs -->
			<xs:attribute name="href" type="xs:anyURI" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="amigos">
		<xs:complexType>
			<xs:sequence>
                <!-- Cada usuario puede tener infinitos amigos, pero al menos uno (Si pone la etiqueta 'amigos') -->
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="usuario" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <!-- Tipos nuevos para validaci칩n de atributos -->
        
    <xs:simpleType name ="diaTipo">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name ="mesTipo">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name ="a침oTipo">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2022"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== uo277915/sew_ext_2022/xml/friendships_for_schema.xml
<?xml version="1.0" encoding="UTF-8"?>

<usuarios xmlns="http://www.uniovi.es/alumnos"
	xsi:schemaLocation="http://www.uniovi.es/alumnos friendships.xsd" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <usuario id="1" nickname="sitoo">
        <datos>
            <fechaNacimiento dia='28' mes='10' año='2001' />
            <estado mensaje="Jugando un rato!" />
            <fotoPerfil href="media/img/usuarios/user1" />
        </datos>
        <amigos>
            <usuario id="2" nickname="paquiLaJugadora">
                <datos>
                    <fechaNacimiento dia='17' mes='6' año='2006' />
                    <estado mensaje="LOL jajaja" />
                    <fotoPerfil href="media/img/usuarios/user2" />
                </datos>
            </usuario>
            <usuario id="3" nickname="juanito33">
                <datos>
                    <fechaNacimiento dia='20' mes='5' año='1997' />
                    <estado mensaje="Soy un buen gamer" />
                </datos>
                <amigos>
                    <usuario id="2" nickname="paquiLaJugadora">
                    </usuario>
                    <usuario id="4" nickname="willirex">
                        <datos>
                            <fechaNacimiento dia='1' mes='1' año='1985' />
                            <estado mensaje="Compra mis nfts!!" />
                            <fotoPerfil href="media/img/usuarios/willy" />
                        </datos>
                    </usuario>
                    <usuario id="5" nickname="peterlanguila">
                        <datos>
                            <fechaNacimiento dia='5' mes='5' año='1970' />
                            <estado mensaje="uwu" />
                            <fotoPerfil href="media/img/usuarios/user5" />
                        </datos>
                        <amigos>
                            <usuario id="7" nickname="juanito">
                                <datos>
                                    <fechaNacimiento dia='30' mes='11' año='2002' />
                                    <estado mensaje="holiii" />
                                    <fotoPerfil href="media/img/usuarios/user7" />
                                </datos>
                                <amigos>
                                    <usuario id="1" nickname="sitoo">
                                    </usuario>
                                </amigos>
                            </usuario>
                        </amigos>
                    </usuario>
                    <usuario id="6" nickname="eldiablo666">
                        <datos>
                            <fechaNacimiento dia='6' mes='6' año='2006' />
                            <estado mensaje="¡MUAJAJAJAJA!" />
                            <fotoPerfil href="media/img/usuarios/user6" />
                        </datos>
                        <amigos>
                            <usuario id="4" nickname="willirex">
                            </usuario>
                        </amigos>
                    </usuario>
                </amigos>
            </usuario>
        </amigos>
    </usuario>
</usuarios>
